### ISSUE TITLE
Horizontal Scrolling

### ISSUE THREAD

**Issue by vigneshhari** [vigneshhari/summit_website#9]
The Website on Mobile View ( Low DPI Devices ) has a horizontal scroll which needs to be removed

To imitate this, inspect the website on chrome and select a low DPI device ( Galaxy s5 or s3 or so ) and try scrolling horizontally

**Comment by vigneshhari** [comment]
The issue persists on the home screen

**Comment by NikhilMTomy** [comment]
Probably solved by b0b47b9cf17aef667829773185faf0c0df7705d7

**Comment by vigneshhari** [comment]
Closing issue
